### ISSUE TITLE
Spelling error detection

### ISSUE THREAD

**Issue by baabaablackgoat** [MGF1998/SolsticeBot#66]
In all seriousness: Ignoring edits below a (configurable) threshold...
OR!
let the bot shitpost the failed spelling... three times.

**Comment by RillingDev** [comment]
( ° w °)

**Comment by baabaablackgoat** [comment]
It seems to detect the spelling error, but it doesn't shitpost.
...yet.

**Comment by baabaablackgoat** [comment]
3424a5a
...timestamps can be horrible
